language: android

jdk:
  - oraclejdk8
  
android:
  components:
    - build-tools-25.0.2
    - android-25
  
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    
  before_script:
    - android update sdk --no-ui --filter build-tools-25.0.2,android-25
